[package]
name = "dumpster"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["Clayton Ramsey"]
description = "Cycle-tracking garbage collection library"
repository = "https://github.com/claytonwramsey/dumpster"
readme = "../README.md"
keywords = ["dumpster", "garbage collector"]
categories = ["data-structures", "memory-management"]

[features]
coerce-unsized = []

[dependencies]
once_cell = "1.18.0"

[dev-dependencies]
fastrand = "2.0.0"